### ISSUE TITLE
Credit card expiry date not valid for current month

### ISSUE THREAD

**Issue by wm-git** [formvalidation/support#123]
We are in the 4th month of 2015 and the credit card expiry date should be valid
![valid](https://cloud.githubusercontent.com/assets/12076369/7288272/47eb67a2-e9a2-11e4-933c-f38b406d7340.jpg)
. See attached.

**Comment by nghuuphuoc** [comment]
Thank for reporting.
That's because I assume that :

> For demonstrating purpose, the expiration date is treated as valid if it is in the range of next month and next 10 year

Anyway, in the fact that the current month is still valid, the [Validating credit card expiration date](http://formvalidation.io/examples/validating-credit-card-expiration-date/) example is updated.

![cc-date](https://cloud.githubusercontent.com/assets/4226036/7289715/106c94ee-e99e-11e4-8d09-91e5b89a82ff.png)
