### ISSUE TITLE
VAT validator doesn't work right

### ISSUE THREAD

**Issue by Stiropor** [formvalidation/support#181]
VAT validator doesn't work like it should, it acts more like notEmpty validator because it accepts anything. See image below.
![screen shot 2015-06-29 at 11 11 56](https://cloud.githubusercontent.com/assets/365876/8404750/d477ef88-1e4f-11e5-94dd-0819067e3bd0.png)

**Comment by nghuuphuoc** [comment]
Thank for reporting that.

Actually, it will treat the VAT number as valid if it can't define the country code.
(Since the VAT validator might not cover/update all countries)
I will update the demo which includes a select box for choosing the country.

**Comment by nghuuphuoc** [comment]
Now the [example](http://formvalidation.io/validators/vat/#example) requires to choose the country:

![vat-validator](https://cloud.githubusercontent.com/assets/4226036/8451789/0b9fb4c0-2010-11e5-889f-4d61986531d4.png)

It will inform if you enter an invalid VAT number such as in your comment.

**Comment by Stiropor** [comment]
Or the validator could just check the first two characters, resolve the country, and check for valid number of digits.
To make this really proper numbers could also be checked/validated, example for Slovenian VAT: each digit is multiplied by it's index and if "11 - (sum / 11)" is same as number of digits than VAT number is valid. Not sure about other countries though. But I guess that's beyond the scope of this validator plugin :)

**Comment by nghuuphuoc** [comment]
> Or the validator could just check the first two characters, resolve the country, and check for valid number of digits

Yes, this is exactly how it works. The country code is defined automatically from first 2 characters.
But the problem is that the VAT validator might not cover all up-to-date countries, so it will treat the input as valid if the country code doesn't belong to the list of supported one.


> example for Slovenian VAT: each digit is multiplied by it's index and if "11 - (sum / 11)" is same as number of digits than VAT number is valid

Yes, all countries are done as this way. Behind the scenes, the validator calculate and compare with the check digits.
You can take a look at the source placed inside the `src/js/validator/vat.js` :)

**Comment by Stiropor** [comment]
Amazing :+1: Thanks for all the work on this plugin :)
