### ISSUE TITLE
Question: How to dynamically make div tag visible on dropdown select?

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#22]
_From @mhtchong1989 on February 7, 2015 7:52_

I have this form with a lot of input fields. One of the input fields is a dropdown menu wherein once the user selects one, I want 2 additional input fields to appear below it.

Here is the screenshot of the form:

![untitled](https://cloud.githubusercontent.com/assets/9627593/6091310/2ced77fc-aee1-11e4-9c03-1f0ff421aff3.png)

As you can see in the screenshot, I have already put the two input fields: Government Permit and Government Recognition Number. By default, I want both of them to be hidden (without taking the space while hidden). They will only appear once the 'Existing' option is selected. If 'New' is selected, nothing happens. 

_Copied from original issue: formvalidation/formvalidation#1414_

**Comment by nghuuphuoc** [comment]
@mhtchong1989
Is it just a normal jQuery question (nothing related to FormValidation)?

**Comment by sades** [comment]
I do have a question about this type of form and if it can be done ill buy it inmidiatly.

Having a form like the one mentioned that you hide and show divs with different kind of inputs for example on my drop down if i select 1 it will show a text box can this be validated only if on the menu or on a radio list is selected or checked the hidden fields will now show and be validated, now i select option 2 on the dropdown select option list and instead of showing the text box it gives me another input but only a list of check box now the other field should not be validated but not it should require me to select at least one option from the check box.

Hope this makes sense sorry my poor english now can this be done with this?

**Comment by nghuuphuoc** [comment]
@sades 
I wish you could create a sample [fiddle](http://jsfiddle.net/) for me.
The [toggling](http://formvalidation.io/examples/toggle/) and [Enabling validators](http://formvalidation.io/examples/enable-validator/) examples might help you.

**Comment by sades** [comment]
@nghuuphuoc 

The toggling seems the one I might need, I just made a dummy form of something I have to do very soon [fiddle test!](http://jsfiddle.net/sadesades/uhLq037s/) 
I guess its possible, with the toggling might have to change and not use class but instead direct styling.

And last question if i have for example more than 2 items inside one same hidden field but i just need one to be required for and the other one not required is it possible?

Thanks

**Comment by nghuuphuoc** [comment]
@sades 
> if i have for example more than 2 items inside one same hidden field but i just need one to be required for and the other one not required is it possible

I think it's possible as long as the not-required field doesn't have any validator rules.

**Comment by sades** [comment]
Some fields might have for example check more at least 2 check box option or place a valid email, or a valid phone address are you referring to that kind of validator rules?

**Comment by sades** [comment]
O and another question when I buy it do it get updates and for how long?

**Comment by sades** [comment]
sorry the dumb question just saw you do give lifetime updates sorry.

**Comment by sades** [comment]
Ok just bought it :)

**Comment by nghuuphuoc** [comment]
@sades Thank you :+1:
