### ISSUE TITLE
GitHub site confusion issue 

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/support#26]
I am confused with the sites under 

https://github.com/formvalidation/formvalidation here at Github. I know 

https://github.com/formvalidation/formvalidation.io is the site for at least one of the jquery plugins. WHat is https://github.com/formvalidation/formvalidation ?? This seems to also be a plugin... and then there is

https://github.com/formvalidation/support which I guess is the support site for both?

Sorry but I start to get confused when I search for https://github.com/formvalidation/formvalidation.io support and keep running into https://github.com/formvalidation/formvalidation site which is so similar.
'Can you explain the relation?

**Comment by nghuuphuoc** [comment]
@haldiggs 
* https://github.com/formvalidation/formvalidation is the main repos containing the source code of plugin
* https://github.com/formvalidation/formvalidation.io is the repos containing the source of official website (formvalidation.io)

Since https://github.com/formvalidation/formvalidation/issues consists of many old issues, and many questions I got through emails, chat, Twitter/Facebook/Google+, I think it's better to create an only one repos where user can raise issue.

That's why we're here. 
The users can't submit the issue on https://github.com/formvalidation/formvalidation.io anymore, and soon can't do this on https://github.com/formvalidation/formvalidation.
