### ISSUE TITLE
only validate when a value is present

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/support#27]
I have an email field on a form. I am using the example from

    http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address
I am not requiring this field but the validator fires and makes the field green/checked. Is there a way to only fire this validation if a value is present. Its a bit much to turn every field on the screen green since they are not used.

thanks and btw I will be buying the library as soon as we can get everything working.

**Comment by nghuuphuoc** [comment]
Behind the scenes, all validators except [notEmpty](http://formvalidation.io/validators/notEmpty/) will not perform their jobs when the field is empty and mark it as valid.
That's why you still see green color and tick icon even when the field is empty.

If you don't want to see that, look at the [Hiding success class and tick icon when field is empty](http://formvalidation.io/examples/hiding-success-class/#hiding-success-class-and-tick-icon-when-field-is-empty) example.

**Comment by haldiggs** [comment]
Thank you Nghuuphuoc!
