### ISSUE TITLE
how to validate two jqueyUI datepicker 

### ISSUE THREAD

**Issue by VipinSharma007** [formvalidation/support#330]
I am unable to validate two jqueryUI datepicker as you have done only for one jqueryUI datepicker to validate birthday in the example. Actually i want to use fromdate and todate two fields in my form and todate should be greater that fromdate

**Comment by nghuuphuoc** [comment]
* To use two jQuery UI datepicker in the same forms, you can use

```javascript
$('#profileForm')
    .formValidation({
        ...
    })
    .find('[name="startDate"]')
    	.datepicker({
                onSelect: function(date, inst) {
		        $('#profileForm').formValidation('revalidateField', 'startDate');
    		}
         })
        .end()
    .find('[name="endDate"]')
    	.datepicker({
                onSelect: function(date, inst) {
		        $('#profileForm').formValidation('revalidateField', 'endDate');
    		}
        })
        .end()
```

* In order to compare the start and end dates, you should look at the [Validating start and end datetimes](http://formvalidation.io/examples/validating-start-end-datetimes/#comparing-dates) example.

Here is the [working fiddle](http://jsfiddle.net/nghuuphuoc/fojx8zwo/1/) and result:

![two-datepickers](https://cloud.githubusercontent.com/assets/4226036/10329877/ef64f85a-6cf0-11e5-988b-487d7f8af360.png)

**Comment by VipinSharma007** [comment]
Thanks for kind support
