### ISSUE TITLE
HTML5 type="date" Won't Validate

### ISSUE THREAD

**Issue by manovraresoft** [formvalidation/support#392]
Take a look at my fiddle:

http://jsfiddle.net/manovraresoft/oqo1ss1o/1/

I want my web application to be mobile friendly. Especially when it comes to dates; so I am using type="date" when asking the use for date input. The problem I keep running in to is that in browsers the date never becomes valid.

**Comment by nghuuphuoc** [comment]
* The date picker doesn't support `type="date"` element, because you actually don't need to use `type="date"` while having date picker in your hand.

Let's look at this fiddle which uses both date picker and `type="date"`:
http://jsfiddle.net/nghuuphuoc/oqo1ss1o/4/

Choosing a date from the picker doesn't update the field as you want.

* Also, it's not friendly when using both things. The user will get confused because they will see 2 date pickers, one from the plugin, and one from the browser:

<img width="712" alt="dtae-pickers" src="https://cloud.githubusercontent.com/assets/4226036/11229579/57cd8814-8dc9-11e5-8422-e3adcacff233.png">

* My advice is that you should 
- either use a date picker with `type="text"` 
- or not use a date picker and `type="date"`: http://jsfiddle.net/nghuuphuoc/oqo1ss1o/5/
