### ISSUE TITLE
Date Validator - support for '.' as seperator

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#44]
_From @marvkis on March 3, 2015 8:57_

Hi,

in Europe we have many countries that have a '.' as Date-Seperator like DD.MM.YYYY.

In the src/js/validator/date.js the validator tries to automatically detect the seperator in line 83, but it only tests for '-' and '/' as candidate. Can you add support to also test for an '.' as seperator, like
separator = (date.indexOf('/') !== -1) ? '/' : ((date.indexOf('-') !== -1) ? '-' : ((date.indexOf('.') !== -1) ? '.' : null));

Thanks & Bye,
     marvkis

_Copied from original issue: formvalidation/formvalidation#1444_

**Comment by nghuuphuoc** [comment]
@marvkis
Thank for the feedback.
At the moment, does the ```separator``` option help? See http://formvalidation.io/validators/date/

**Comment by marvkis** [comment]
Hi,
Thanks for this hint, i already implemented a workaround with it. But it's more like a hack, because i get the date formats from moment.js and moment.js does not provide something that i can use as separator directly form it's i18n implementation. So it would be great to have this implemented in formvalidation directly ;)

Thanks & Bye,
    marvkis

**Comment by nghuuphuoc** [comment]
@marvkis 
Supporting dot (.) separator is implemented and will be available in the next v0.6.2.
Thank you!

**Comment by nghuuphuoc** [comment]
@marvkis
dot (.) separator is officially [supported](http://formvalidation.io/validators/date/)
