### ISSUE TITLE
Conditional Validation: TypeError: this.options.fields[a] is undefined

### ISSUE THREAD

**Issue by joekuzma** [formvalidation/support#595]
I'm using version 0.7.1, and I am attempting to do conditional validation when a pull down is selected.

I have two DIV's, one hidden and one viewable.. each contains a text field that needs validation.  But if one DIV is hidden that text field should be ignored.

I've been able to create a Fiddle that duplicates the error at:

https://jsfiddle.net/cpwezkvy/12/ 

```
The error:
TypeError: this.options.fields[a] is undefined
https://admin.adworldmedia.com/javascripts/vendor/formvalidation/formValidation.min.js
Line 10
```

**Comment by nghuuphuoc** [comment]
In the current code:

```javascript
$(document).ready(function() {
    showMembers();

    $('select').on('change',function() {
  	...
    });
    $('#form1').formValidation(...);
});
```

You call `showMembers()` first, and this method make other calls 
```javascript
$('#form1').formValidation('enableFieldValidators', 'txtCost', true);
$('#form1').formValidation('enableFieldValidators', 'txtCPC', false);
```
Because `showMembers()` is called before `$('#form1').formValidation(...)`, so at that moment the `FormValidation` instance has NOT been created yet.

So calling `$('#form1').formValidation('enableFieldValidators')` inside `showMembers()` will throw an exception.

The solution is you need to call `showMembers` AFTER initializing `$('#form1').formValidation(...)`:

 ```javascript
$(document).ready(function() {
    $('select').on('change',function() {
  	...
    });
    
    // Init the plugin first ...
    $('#form1').formValidation(...);

    // ... and then show the members
    showMembers();
});
```
