### ISSUE TITLE
Has the formValidation team abandoned this project?

### ISSUE THREAD

**Issue by wvmstr** [formvalidation/support#779]
Looked so promising, but without the support from their team this project is doomed to fail.

**Comment by nghuuphuoc** [comment]
Absolutely, no. 
We are so sorry if the supporting isn't in time as you requested, but we will try.
The reason is that we have been working hard to preparing for the next big v1 as you can see a lot of new things [here](https://twitter.com/formvalidation/status/828656111800627201).

Some of the problems from this Github are actually done in the next v1 development version.
